name: 'Pull Request Notifier'
description: 'Sends notifications to Slack, Discord, or Teams for Pull Request events'
author: 'Leticia Mantovani'
inputs:
  service:
    description: 'Notification service: slack, discord, or teams'
    required: true
  webhook_url:
    description: 'Webhook URL for the selected service'
    required: true
  pr_title:
    description: 'Title of the Pull Request'
    required: true
  pr_url:
    description: 'URL of the Pull Request'
    required: true
  pr_action:
    description: 'Action performed on the PR'
    required: true
  pr_author:
    description: 'Author of the Pull Request'
    required: true
  repo_name:
    description: 'GitHub repository name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SERVICE: ${{ inputs.service }}
    WEBHOOK_URL: ${{ inputs.webhook_url }}
    PR_TITLE: ${{ inputs.pr_title }}
    PR_URL: ${{ inputs.pr_url }}
    PR_ACTION: ${{ inputs.pr_action }}
    PR_AUTHOR: ${{ inputs.pr_author }}
    GITHUB_REPOSITORY: ${{ inputs.repo_name }}
branding:
  icon: 'bell'
  color: 'purple'
