name: Notify Slack on Pull Request

on:
  pull_request:
    types:
      - opened
      - closed
      - review_requested
      - review_request_removed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_ACTION=${{ github.event.action }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Slack notification script
        run: python notify.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_TITLE: ${{ env.PR_TITLE }}
          PR_URL: ${{ env.PR_URL }}
          PR_ACTION: ${{ env.PR_ACTION }}
          PR_AUTHOR: ${{ env.PR_AUTHOR }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
