name: Lint and Test

on:
  push:
    paths:
      - 'notifier/**'
      - 'tests/**'
      - 'requirements*.txt'
      - '.github/workflows/test.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: flake8 notifier
      - name: Test
        run: pytest tests
